name = "extra-vision-inference-production"
main = "index.ts"
compatibility_date = "2024-01-01"

[vars]
ROBOFLOW_WORKSPACE = "purple"
ROBOFLOW_WORKFLOW_ID = "extra-vision-ai"

[env.staging]
name = "extra-vision-inference-staging"
[env.staging.vars]
ROBOFLOW_WORKSPACE = "purple"
ROBOFLOW_WORKFLOW_ID = "extra-vision-ai"

